#!/usr/bin/env python
import os , io , sys
import urllib , urllib2 , cookielib

####################### SETTING ########################

login_url = "http://zerojudge.tw/Login"
submit_url = "http://zerojudge.tw/Solution.api"

cookiefile = 'cookie_zj.txt'
cookiefile = os.path.expanduser('~/bin/' + cookiefile)

your_account = "" # stuff your account here
your_pw = "" # stuff your password here

####################### CHECK PARAMETER ################

if len(sys.argv) > 3 or len(sys.argv) < 2:
    print "give me (one file name) || (one file name , one problem ID) as parameter"
    quit()
    
if len(sys.argv) == 2 :
    problemid = os.path.basename(os.getcwd())
else:
    problemid = sys.argv[2]

#submit_url = submit_url + problemid
submit_file = sys.argv[1]
ext = os.path.splitext(submit_file)[-1]



if ext == '.c':
    language = 'C'
elif ext in ['.cpp' , '.C' , '.cc' , '.CPP' , '.cxx' , 
        '.cp' , '.cc' , '.c++']:
    language = 'CPP'
elif ext == '.java':
    language = 'JAVA'
elif ext == '.py':
    language = 'PYTHON'
elif ext in ['.pas' , '.pp']:
    language = 'PASCAL'
else:
    print 'cannot indentify file type'
    quit()

#user_agent = 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)'

####################### LOG IN #########################
cookieJar = cookielib.MozillaCookieJar()
if os.path.exists(cookiefile):
    cookieJar.load(cookiefile, ignore_discard=True, ignore_expires=True)
    opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cookieJar))
else:
    cookieJar = cookielib.MozillaCookieJar(cookiefile)
    opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cookieJar))
    login_page = opener.open(login_url)
    IP = InputParser()
    IP.feed(login_page.read())
    info = login_page.info()
    token = info.getheader('set-cookie')[0:43]
    post_data = urllib.urlencode({
        "account" : your_account  , 
        "passwd" :  your_pw ,
        "returnPage" : "/Index" , 
        "token" : token_value
        })
    opener.addheaders = [
            ('Host', 'zerojudge.tw') , 
            ('Connection', 'keep-alive') ,
            ('Cache-Control', 'max-age=0') , 
            ('Upgrade-Insecure-Requests', '1') , 
            ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36') , 
            ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8') , 
            ('Referer', 'http://zerojudge.tw/Login') , 
            ('Accept-Encoding', 'gzip, deflate, sdch') , 
            ('Accept-Language', 'zh-CN,zh;q=0.8,zh-TW;q=0.6') , 
            ('Cookie', token)
            ]
    result = opener.open(login_url , post_data);
    cookieJar.save(ignore_discard=True , ignore_expires=True)
    #print result.read()

####################### SUBMIT #########################

codeFile = io.open(submit_file , 'r' , encoding = 'UTF-8')
code = codeFile.read()

submission_data = urllib.urlencode({
    "action" : "SubmitCode" , 
    "language" : language , 
    "code" : code , 
    "problemid" : problemid , 
    })

try:
    result = opener.open(submit_url , submission_data);
    print result.read()
except urllib2.HTTPError , e:
    print e.code
    print e.reason
else:
    print "language : " , language
    print "problemid : " , problemid
    print "submitURL : " , submit_url
    print "code : "
    print code
    print "submit done!"
